# Generated by Django 2.1.5 on 2020-01-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='Tutorial_published',
            new_name='tutorial_published',
        ),
    ]
